#
# CORE
# Copyright (c)2010-2012 the Boeing Company.
# See the LICENSE file included in this distribution.
#
''' Sample user-defined service.
'''

import os

from core.service import CoreService, addservice
from core.misc.ipaddr import IPv4Prefix, IPv6Prefix

class AdsbIn(CoreService):
    ''' This is a sample user-defined service.
    '''
    # a unique name is required, without spaces
    _name = "AdsbIn"
    # you can create your own group here
    _group = "Aviation"
    # list of other services this service depends on
    _depends = ()
    # per-node directories
    _dirs = ()
    # generated files (without a full path this file goes in the node's dir,
    #  e.g. /tmp/pycore.12345/n1.conf/)
    _configs = ('adsbin.cfg', 'adsbin.sh')
    # this controls the starting order vs other enabled services
    _startindex = 50
    # list of startup commands, also may be generated during startup
    _startup = ('sh adsbin.sh',)
    # list of shutdown commands
    _shutdown = ()

    @classmethod
    def generateconfig(cls, node, filename, services):
        ''' Return a string that will be written to filename, or sent to the
            GUI for user customization.
        '''
        if filename == "adsbin.sh":
            cfg = "#!/bin/sh\n"
            cfg += "# auto-generated by AdsbIn (adsbin.py)\n"
            cfg += "python -m adsb.adsb_in.adsb_in -c adsbin.cfg\n"
        elif filename == "adsbin.cfg":
            soma = 0
            for ch in node.name:
                if ch.isdigit():
                    soma += int(ch)
            cfg = "[General]\n"
            cfg += "id = %s\n" % node.name
            cfg += "destinations = Dump1090 asterix\n\n"
            cfg += "[Dump1090]\n"
            cfg += "type = dump1090\n"
            cfg += "server = localhost\n"
            cfg += "port = 30001\n\n"
            cfg += "[asterix]\n"
            cfg += "type = asterix\n"
            cfg += "server = 127.0.0.1\n"
            cfg += "port = %s\n\n" % (40000+soma)

        return cfg

    @staticmethod
    def subnetentry(x):
        ''' Generate a subnet declaration block given an IPv4 prefix string
            for inclusion in the config file.
        '''
        if x.find(":") >= 0:
            # this is an IPv6 address
            return ""
        else:
            net = IPv4Prefix(x)
            return 'echo "  network %s"' % (net)

# this line is required to add the above class to the list of available services
addservice(AdsbIn)
